spring:
  datasource:
    name: poker
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/poker_random?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: bingoZAQ!2wsx
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  application:
    name: Bingo platform

  encrypt:
    debug: false
    threadLocal: true
    keyField: k
    valueField: v
    key: 213435fsdfsdfsad
    separateRsa: 12!%$&*56789qwe12

  thymeleaf:
    prefix: classpath:/templates
    cache: false

feign: 
  backWalletIp: http://127.0.0.1:8002/backstage
  ssoServerIp: http://127.0.0.1:8183/sso
  timeOutMillis: 5000

client:
  clientId: 7001BCAFE0F64ACBB238182349C4F1EE9F4Z8ZWF14
  clientSecret: 96A4B88AD044331F3883489F4Z9380ZC

logging:
  level: 
    #打印mybatis的sql，以下读的mybatis对应的方法接口所在的包，并不是mapper.xml所在的包
    com:
     bingo:
      quotation:
       mapper: debug

swagger:
  docket:
    Security: #分组
      title: Bingo user
      description: 管理
      version: 1.0.0
      base-package: com.bingo.user
      contact:
          name:
