spring:
  datasource:
    name: poker
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/poker_random?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: bingoZAQ!2wsx
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis: 
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    #连接超时时间
    timeout: 10000
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0

  application:
    name: Bingo platform

feign:
  backWalletIp: http://172.18.251.149/backstage
  ssoServerIp: http://172.18.251.149/sso
  timeOutMillis: 5000

client:
  clientId: 7001BCAFE0F64ACBB238182349C4F1EE9F4Z8ZWF14
  clientSecret: 96A4B88AD044331F3883489F4Z9380ZC

